### ISSUE TITLE
How to configure with free account?I am getting error while configuring as per the instruction.

### ISSUE THREAD

**Issue by vijayvikma** [webhookrelay/home-assistant#5]
Hello Experts,

While configuring Webhookrelay in HA i am getting below error.I can see with free account we can use 150 webhoockrelay transaction per month.but not able to configure.Please help me in this case.

**I  tried with duckDns account in that case it gives below error.**
 [✗] Your plan doesn't include custom subdomains, set 'subdomain' for tunnel 'home-assistant' to an empty string, 
     or upgrade your plan here: https://my.webhookrelay.com/account/plan 

**Then tried with removing domain in that case i got below error**

::: ::: ::: ::: ::: ::: ::: ::: ::: ::: ::: 
 [i] Bidirectional tunnelling enabled... 
 [✗] Failed to ensure tunnel home-assistant, error: API error (412): tunnel amount (1) for your current plan reached 

**My configuration looks like below.Tried with few more combinations but no luck so far.**

{
  "key": "key from web hoock",
  "secret": "secure code from weeb hook",
  "forwarding": [],
  "tunnels": [
    {
      "name": "home-assistant",
      "destination": "http://192.168.0.11:8123",
      "protocol": "tls",
      "domain": "vvhome.duckdns.org"
    }
  ],
  "duck_dns": {
    "token": "Duck DNS token",
    "accept_terms": true
  },
  "cloudflare": {
    "email": "",
    "api_key": ""
  },
  "tunnels_enabled": true,
  "forwarding_enabled": false
}

**Comment by osroflo** [comment]
Using a free plan, you only have access to 1 tunnel. 
Try this:

1. Make sure to remove any tunnel manually added using the dashboard (GUI). 
2. Create the tunnel using the CLI:

```
relay connect --name www http://localhost:4000
Connecting: 
http://syzkyvybmwcn37.webrelay.io <----> http://localhost:4000
Using default region from settings 
2021-04-29 12:23:46.859	INFO	client starting	{"version": "1.26.1", "tunnels": ["8ac13d3c-e5d6-4141-8bd4-92f2048e25d2"]}
2021-04-29 12:23:46.860	INFO	initiating tunnel connection
2021-04-29 12:23:46.860	INFO	dialing server...	{"network": "tcp", "addr": "tnl.webrelay.io:9800"}
2021-04-29 12:23:47.839	INFO	adding HTTP tunnel syzkyvybmwcn37.webrelay.io ---> http://localhost:4000
2021-04-29 12:23:47.839	INFO	adding WS tunnel syzkyvybmwcn37.webrelay.io ---> localhost:4000
2021-04-29 12:23:47.839	INFO	tunnel proxy configuration updated

```
